# Generated by Django 5.1.6 on 2025-02-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_shipment', models.DateTimeField(null=True)),
                ('datetime_sending', models.DateTimeField(null=True)),
                ('typename', models.CharField(max_length=50, null=True)),
                ('serialNum', models.CharField(max_length=10, null=True)),
                ('material', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
