# Generated by Django 5.1.6 on 2025-02-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_nails_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='nails',
            name='material',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
